const CANHCAM_APP = {
    "DISPLAY_FOOTER": 600,
    "ACTIVE_FIXED_FOOTER": true,
    "ACTIVE_BACKTOTOP": true,
    "DISPLAY_BACKTOTOP": 100,
    "CHANGE_GRID": 991,
    "ACTIVE_RESPONSIVE": true,
    "DEV_MODE": true,
    "DEV_MODE_GIRD_FULL": false
}
