const CANHCAM_APP = {
	"ACTIVE_FIXED_HEADER": false,
	"HEADER_TRANPARENT": false,
	"ACTIVE_HEADER_POSITION": 1,
	"ACTIVE_PADDING_MAIN": true,
	"ACTIVE_FIXED_FOOTER": true,
	"DISPLAY_FOOTER": 600,
	"ACTIVE_RESPONSIVE": true,
	"ACTIVE_BACKTOTOP": true,
	"DISPLAY_BACKTOTOP": 100,
	"CHANGE_GRID": 991,
	"DEV_MODE": true,
	"DEV_MODE_GIRD_FULL": false
}
